version: '3.7'
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - node-network
    depends_on:
      - mongodb

  mongodb:
    container_name: database
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
